In [ ]:
Part 1 - Numpy

Use this dataset for the first 4 questions.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]

3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

Part 2 - Pandas

1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

#Part 1

In [2]:
import numpy as np

In [3]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

### Q1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.


In [11]:
a = np.array([[1,5,9], [2, 6, 9]])
b = np.array([[3,7,11], [-9, 8, 2]])

In [12]:
np.concatenate((a,b), axis=0)

array([[ 1,  5,  9],
       [ 2,  6,  9],
       [ 3,  7, 11],
       [-9,  8,  2]])

In [13]:
np.concatenate((a,b), axis=1)

array([[ 1,  5,  9,  3,  7, 11],
       [ 2,  6,  9, -9,  8,  2]])

### Q2. Find common elements between A and B. [Hint : Intersection of two sets]


In [14]:
np.intersect1d(a,b)

array([2])

### Q3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [15]:
np.where(np.logical_and(a > 5, a < 10))

(array([0, 1, 1]), array([2, 1, 2]))